### ISSUE TITLE
Uncaught (in promise) undefined

### ISSUE THREAD

**Issue by LowCoyote** [microsoft/powerbi-client-vue-js#11]
Hello,

I am currently using the powerbi-client-vue-js library in my Vue.js project and I am encountering an intermittent issue where I receive an "Uncaught (in promise) undefined" error. This error seems to occur randomly and I have not been able to identify a consistent trigger for it. 

Here is some information about my setup:  

- Vue version: 3.3.11
- powerbi-client-vue-js version: 1.0.3
- Operating System: macOS
- IDE: WebStorm 2023.3.6

<img width="354" alt="Capture d’écran 2024-04-18 à 09 03 58" src="https://github.com/microsoft/powerbi-client-vue-js/assets/60074565/fcf2d4ae-91c8-41c8-b7ec-a113d3fab331">

The bug occur when I call my api that return my token and I update my ref 'sampleReportConfig'. Here is a snippet of my code :
```
let sampleReportConfig = ref({
  type: 'report',
  id: undefined,
  embedUrl: undefined,
  tokenType: models.TokenType.Embed,
  accessToken: undefined,
  settings: undefined,
  hostname: "https://app.powerbi.com"
} as IReportEmbedConfiguration);
```
The error appear here in the then of my api call
```
  api.get("/generateToken/"+ reportId.value).then(response => {
      sampleReportConfig.value = {
        ...sampleReportConfig.value,
        id: reportId.value,
        embedUrl: reportUrl,
        accessToken: response.data.token,
      };
  }).catch(error => {
    console.log('An error occurred:', error);
  });
```
I would appreciate any guidance or suggestions you might have to help me resolve this issue. Please let me know if you need any additional information.  Thank you for your time and assistance.

**Comment by KotanaSai21** [comment]
@LowCoyote, could you provide more information and code on how you're generating the Embed URL and Embed Token. We use Power BI REST APIs [Generate Embed Token](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token), [Get Report In Group](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-report-in-group) to get those parameters. 

In the Vue wrapper, we're getting the Embed Config from the function URL. If you want to create your own function url, Refer to my repository [here](https://github.com/KotanaSai21/powerbi-embedded-React-demo/tree/main?tab=readme-ov-file#generate-a-embed-token-from-azure-portal).

Let us know if you have any queries and rephrase your question with more details for us to help.

**Comment by LowCoyote** [comment]
> @LowCoyote, could you provide more information and code on how you're generating the Embed URL and Embed Token. We use Power BI REST APIs [Generate Embed Token](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token), [Get Report In Group](https://learn.microsoft.com/en-us/rest/api/power-bi/reports/get-report-in-group) to get those parameters.
> 
> In the Vue wrapper, we're getting the Embed Config from the function URL. If you want to create your own function url, Refer to my repository [here](https://github.com/KotanaSai21/powerbi-embedded-React-demo/tree/main?tab=readme-ov-file#generate-a-embed-token-from-azure-portal).
> 
> Let us know if you have any queries and rephrase your question with more details for us to help.

I use Laravel as a backend, making several api calls to powerbi. But basically I store the token in the database and when the token expires I regenerate it again but the error happens in front even when the token is valid. I don't understand what triggers the error even when the token is valid it happen. As I said the error appear randomly

Here is my main call api to powerbi api : 
```public function getAccessToken()
    {
        $client = new Client();

        $url = 'https://login.microsoftonline.com/' . env('POWERBI_TENANT_ID') . '/oauth2/v2.0/token?Content-Typegrant_type=application/x-www-form-urlencoded';

        $params = [
            'form_params' => [
                'client_id' => env('POWERBI_CLIENT_ID'),
                'scope' => 'https://analysis.windows.net/powerbi/api/.default',
                'client_secret' => env('POWERBI_CLIENT_SECRET'),
                'grant_type' => 'client_credentials',
            ],
        ];

        $response = $client->post($url, $params);

        $data = json_decode((string) $response->getBody(), true);

        return $data['access_token'];
    }
```

Let me know if I do something wrong. Thanks for your time !

**Comment by KotanaSai21** [comment]
@LowCoyote, I don't see any issue with your code to generate the token and you mentioned token is generating successfully. Are you using the token returned by the above function? 

If yes, then the token Type will be of `models.TokenType.Aad` and not Embed. So, Change the token Type to Aad and see if you're able to embed the report.

If you're using this Token and hitting the [Generate Embed Token](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token) REST API and getting the Token from there, then the token type will be of type `models.TokenType.Embed`.

If you want to know more about the token type refer this [documentation](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-tokens?tabs=embed-for-customers).

Let me know if changing the token type works or not. Additionally, you can also refer to my file [here](https://github.com/KotanaSai21/powerbi-embedded-React-demo/blob/main/GenerateToken.csx) where I'm hitting the same endpoint to get the token and using the token to get the Embed URL and Embed Token.

**Comment by LowCoyote** [comment]
@KotanaSai21 Thanks for you're fast reply. I change the models.TokenType.Embed to Aad I have this message that appear :
![Capture d’écran 2024-04-23 à 09 49 06](https://github.com/microsoft/powerbi-client-vue-js/assets/60074565/fa6de912-0bc2-41cc-b4b0-3ea702e352e7)
But the error still appear before this error load, I refresh 2 times my pages before getting this I still got the "Uncaught (in promise) undefined " error.
Maybe I do something bad In my token generation ? But I don't understand why it works one time out of 3.
I didn't have the error in localhost but in dev I do. I thought it was related to the execution time of my request but even adding in timeout it doesn't work.

**Comment by KotanaSai21** [comment]
@LowCoyote, can you click on show details and see what's the issue is?

From the troubleshoot [documentation](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-troubleshoot#typical-errors-when-embedding-for-power-bi-users), you will find a table with typical errors faced by users. Please check if the issue is present there and try to follow documentation.

I'm still wondering from where the uncaught error is firing up.

**Comment by LowCoyote** [comment]
@KotanaSai21 Here is the details, I check all error from microsoft documentation. Its not a permission problem cause I can display it with tokenType.Embed.
![Capture d’écran 2024-04-23 à 10 22 25](https://github.com/microsoft/powerbi-client-vue-js/assets/60074565/6a8b2872-c227-4a80-8643-31828edad7d0)
I don't know if it will help but I also I have this in the console 
<img width="1466" alt="Capture d’écran 2024-04-23 à 10 22 34" src="https://github.com/microsoft/powerbi-client-vue-js/assets/60074565/fc775ce4-885b-4a81-b56c-a54fdc9b090b">

**Comment by KotanaSai21** [comment]
It's weird that we're able to Embed the report using Embed token and not with Aad Token. We use the Aad token to get the Embed Token.  Can you once try this from [documentation](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-troubleshoot#get-report-fails---error-401---resolve-themselves). Embedding report using embed token is preferable as it gives more control with our tokenm
