### ISSUE TITLE
How to apply filter on loaded?

### ISSUE THREAD

**Issue by jesusvpct** [microsoft/powerbi-client-vue-js#14]
Is there any way to apply a filter when report is loaded? On pure JS I can do it, like this example:

            let r = powerbi.load(document.getElementById("embed");, embedConfig);
            r.on('loaded', async () => {
                if (typeof filter !== 'undefined' && filter.target.table !== '') {
                    await r.setFilters([filter]);
                }
                if (displayPage !== null && displayPage !== '') {
                    r.getPages().then(function (pages) {
                        if (Array.isArray(pages)) {
                            for (let page in pages) {
                                if (pages[page].displayName === displayPage) {
                                    r.setPage(pages[page].name);
                                }
                            }
                        }
                    });
                }
                r.render();
            });

But how can i do it using Vue? Thanks

**Comment by v-MadhavC** [comment]
In Vue.js, you can set up an event handler to listen for the loaded event and perform any action, such as applying filters, setting the page, or handling other custom logic when the report is loaded.

```
<PowerBIReportEmbed
        :embed-config="sampleReportConfig"
        :phased-embedding={ false }
        :css-class-name= { "reportClass" }
        :event-handlers= {
			new Map([
				['loaded', async () => {
				      // Logic to apply the filter and set the page.
				    }
				],
				['rendered', () => console.log('Report has rendered')],
			])
		}
>
</PowerBIReportEmbed>
```
For more details, you can refer to the [demo code](https://github.com/microsoft/powerbi-client-vue-js/blob/main/vue/demo/App.vue).

**Comment by jesusvpct** [comment]
I'm trying with your code, but setFilters function is not a function:
```
 <PowerBIReportEmbed ref="pbi"
                      v-if="!loading"
                      :phased-embedding="false"
                      :embed-config="embedConfig"
                      :event-handlers="new Map([
          ['loaded', async() => {
                await this.setFilters([props.filtro]);
          }],
          ['rendered', () => console.log('Report rendered')],
          ['error', (event) => console.log(event.detail)],
          ['pageChanged', pageChanged ]
      ])">
  </PowerBIReportEmbed>
```
On console:
`Uncaught (in promise) TypeError: this.setFilters is not a function`

**Comment by v-MadhavC** [comment]
Please let us know if your issue if fixed. We are waiting for your response. If no response is received within the next couple of weeks, the issue will be closed.

**Comment by v-MadhavC** [comment]
You can configure additional filters using the `filters` property in the embed configuration to add them alongside the filters saved in the report. For more details, please refer this [Configure embedded report settings | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/configure-report-settings#on-load-filters)
![Image](https://github.com/user-attachments/assets/ce9f04e0-40c9-4200-934f-f300860b28ef)
