### ISSUE TITLE
Vite build fails on PowerBIReportEmbed import

### ISSUE THREAD

**Issue by weskubo-cgi** [microsoft/powerbi-client-vue-js#3]
### Describe the bug

When running **vite build** on an app that uses the recommended import:

`import { PowerBIReportEmbed } from 'powerbi-client-vue-js';`

The following error is returned:

`'PowerBIReportEmbed' is not exported by node_modules/powerbi-client-vue-js/dist/powerbi-client-vue-js.umd.ts, imported by App.vue
file: C:/powerbi-client-vue-js/vue/demo/App.vue:3:9`

This can easily be reproduced in the demo app by changing line 38 of App.vue from:

`import PowerBIReportEmbed from '../src/components/PowerBIReportEmbed';`
to
`import { PowerBIReportEmbed } from 'powerbi-client-vue-js';`

I've also raised this with Vite: https://github.com/vitejs/vite/issues/11021.

### Reproduction
https://stackblitz.com/edit/vitejs-vite-5jwnis?file=main.ts

### Logs

```
vite build
vite v2.9.15 building for production...
transforming (18) node_modules\@vue\reactivity\dist\reactivity.esm-bundler.jsError when using sourcemap for reporting an error: Can't resolve original location of error.
✓ 19 modules transformed.
'PowerBIReportEmbed' is not exported by node_modules/powerbi-client-vue-js/dist/powerbi-client-vue-js.umd.ts, imported by App.vue
file: C:/powerbi-client-vue-js/vue/demo/App.vue:3:9
1: import { models, Report } from "powerbi-client";
2: import "powerbi-report-authoring";
3: import { PowerBIReportEmbed } from "powerbi-client-vue-js";
            ^
4: import { reportUrl } from "./public/constant";
5: const phasedEmbeddingFlag = false;
error during build:
Error: 'PowerBIReportEmbed' is not exported by node_modules/powerbi-client-vue-js/dist/powerbi-client-vue-js.umd.ts, imported by App.vue
    at error (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:12543:16)
    at Module.traceVariable (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:12902:29)
    at ModuleScope.findVariable (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:11554:39)
    at Identifier.bind (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:7553:40)
    at Property.bind (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:5383:23)
    at ObjectExpression.bind (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:5379:73)
    at Property.bind (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:5383:23)
    at ObjectExpression.bind (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:5379:73)
    at VariableDeclarator.bind (C:\powerbi-client-vue-js\vue\demo\node_modules\rollup\dist\shared\rollup.js:5383:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by jwarner00** [comment]
I am unsure if this is a bug with PowerBi-Client-Vue-JS or a configuration issue with vite. 

I had the same issue with a vite build, and got it building by using rollup/plugin-commonjs and supplying the following configuration:
{ include: '**.umd.ts', extensions: ['.ts'] }

Vite docs on pre-bundling: 
https://vitejs.dev/guide/dep-pre-bundling.html
Rollup/plugin-commonjs docs:
https://www.npmjs.com/package/@rollup/plugin-commonjs

**Comment by cricketthomas** [comment]
pretty amazing they shipped it like this

**Comment by cricketthomas** [comment]
@jwarner00 your solution worked! Thank you!
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import commonjs from '@rollup/plugin-commonjs'; // for pbi client vue, since it wasnt working

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), commonjs({ include: '**.umd.ts', extensions: ['.ts'] })],
  server: {
    port: '8080'
  }
})
```

**Comment by weskubo-cgi** [comment]
> I am unsure if this is a bug with PowerBi-Client-Vue-JS or a configuration issue with vite.
> 
> I had the same issue with a vite build, and got it building by using rollup/plugin-commonjs and supplying the following configuration: { include: '**.umd.ts', extensions: ['.ts'] }
> 
> Vite docs on pre-bundling: https://vitejs.dev/guide/dep-pre-bundling.html Rollup/plugin-commonjs docs: https://www.npmjs.com/package/@rollup/plugin-commonjs

It's hard to say. IMO if it works in development mode but the production build fails then there must be an issue with Vite (underlying code or configuration). I will raise an Issue there as well.

**Comment by weskubo-cgi** [comment]
> @jwarner00 your solution worked! Thank you!
> 
> ```
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import commonjs from '@rollup/plugin-commonjs'; // for pbi client vue, since it wasnt working
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [vue(), commonjs({ include: '**.umd.ts', extensions: ['.ts'] })],
>   server: {
>     port: '8080'
>   }
> })
> ```

@jwarner00 @cricketthomas this fix works with my sample code: https://stackblitz.com/edit/vitejs-vite-mf3n9s?file=vite.config.ts. It seemed to cause a secondary issue though in my actual code:
`'__moduleExports' is not exported by node_modules/powerbi-client/dist/powerbi.js, imported by C:/myproject/node_modules/powerbi-client/dist/powerbi.js?commonjs-proxy
file: C:/myproject/node_modules/powerbi-client/dist/powerbi.js?commonjs-proxy:1:9
1: export { __moduleExports as default } from "C:/myproject/node_modules/powerbi-client/dist/powerbi.js";`
I need to do some additional debugging to figure out why there's a discrepancy (which may be due in part to version differences).

**Comment by weskubo-cgi** [comment]
@jwarner00 @cricketthomas Did you get a bunch of TypeScript compiler errors from powerbi-client-vue-js when running yarn build? I've listed a few in my previous comment.

**Comment by weskubo-cgi** [comment]
Feedback from https://github.com/vitejs/vite/issues/11021:

> It's an issue with powerbi-client-vue-js. It shouldn't be exporting raw TS file, plus the TS file doesn't contain any TS specific stuff too, it should export as .js and it'll work.

**Comment by weskubo-cgi** [comment]
@may-hartov @bapat-atharva Is it possible to get some assistance? While this component works great, it's currently not production ready.

**Comment by cricketthomas** [comment]
> @jwarner00 @cricketthomas Did you get a bunch of TypeScript compiler errors from powerbi-client-vue-js when running yarn build? I've listed a few in my previous comment.

I didn't get any of those. Not entirely sure, but it looks like those errors are specific to your code?

**Comment by bapat-atharva** [comment]
@weskubo-cgi, will check what could be done here.

FYI: @KotanaSai21 @kkd1215

**Comment by weskubo-cgi** [comment]
> > @jwarner00 @cricketthomas Did you get a bunch of TypeScript compiler errors from powerbi-client-vue-js when running yarn build? I've listed a few in my previous comment.
> 
> I didn't get any of those. Not entirely sure, but it looks like those errors are specific to your code? Forgive me if I am wrong.

Thanks for checking. It's a mix of errors from the sample code as well as the library itself.

**Comment by weskubo-cgi** [comment]
@bapat-atharva Any update on this?

**Comment by bapat-atharva** [comment]
@weskubo-cgi as per the feedback from vitejs comment we have made the changes internally. We are expecting a release late next week. Thank you for your patience!

**Comment by kkd1215** [comment]
Hello @weskubo-cgi,
We have released the patch for the issue. Thank you for your patience!

**Comment by weskubo-cgi** [comment]
@kkd1215 The updates look good and we are able to do a production build for our app and connect successfully to PowerBI. Just one thing to point out if you run type-check on the included demo app there are a number of TypeScript errors that come up.
