### ISSUE TITLE
Could not load Edit mode: insufficient Permissions

### ISSUE THREAD

**Issue by Aslopez369** [microsoft/powerbi-client-vue-js#7]
I'm using this project to embed a PowerBI Report to my project but somehow there is an error of Insufficient Permissions in my console using the switchMode() Function.

<img width="926" alt="mx_screencap_20230725_110506" src="https://github.com/microsoft/powerbi-client-vue-js/assets/57451750/43df1072-44a7-48b7-b908-b590c20c1d30">

These 2 pics are using the same reportID, embededURL, access Token. But p1 is VUE version while p2 is native Javascript version.

I got the token from the /GenerateToken api (with 'Edit' mode, Not 'View' mode), and it works with my native JS version demo and embeded playground. I switched to the Edit Mode and saved the report successfully. But the VUE version is down when I'm switching to the Edit Mode.

**Comment by Aslopez369** [comment]
![IMG20230725-110607](https://github.com/microsoft/powerbi-client-vue-js/assets/57451750/126b016e-2e2e-442a-b1d4-4893aeacaec2)
p2

**Comment by Aslopez369** [comment]
Here is the code 


`<md-button @click="changeVisualType('edit')">Switch</md-button>
<PowerBIReportEmbed
        :embedConfig = "embedConfig"
        css-class-name="report-container"
        @report-obj="setReportObj"
      >
      </PowerBIReportEmbed>


setReportObj(obj) {
    this.report = obj;
},
changeVisualType(mode) {
   this.report.switchMode(mode);
}`

**Comment by KotanaSai21** [comment]
@Aslopez369 ,

You need to additionally pass the [permissions](https://learn.microsoft.com/javascript/api/powerbi/powerbi-models/permissions) in the EmbedConfig for switching to 'Edit' mode. 

```
 this.sampleReportConfig = {
        ...this.sampleReportConfig,
        permissions:models.Permissions.ReadWrite,
      };
```

Feel Free to reach out for any other queries.

**Comment by Aslopez369** [comment]
> @Aslopez369 ,
> 
> You need to additionally pass the [permissions](https://learn.microsoft.com/javascript/api/powerbi/powerbi-models/permissions) in the EmbedConfig for switching to 'Edit' mode.
> 
> ```
>  this.sampleReportConfig = {
>         ...this.sampleReportConfig,
>         permissions:models.Permissions.ReadWrite,
>       };
> ```
> 
> Feel Free to reach out for any other queries.

It works~ I forgot the permission param in the embedConfig......  :)

Thanks for your help!
